name: First Workflow

on: push   # Trigger when code is pushed

jobs:
  hello_job:
    runs-on: ubuntu-latest    # Use GitHub-hosted runner
    steps:
      - name: Print greeting
        run: echo "ðŸ‘‹ Hello from GitHub Actions!"
